<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FEEEBDDDDCCEB")){define("FEEEBDDDDCCEB", __FILE__);global $ž,$Œ•,$„™,$™”‰›,$‘‡˜œ,$ž‹‚‘•,$‚™Ž–…,$Œ™—Š†Œ,$Ž‰•™…†€ˆ,$ž†Œ€™Ÿœ‚˜,$ž’Ž„ˆœ‹‰œ,$˜†…’ŒŒ“•Œ’,$™”–œ““Œ’’›—“,$„”Ÿ•žœ…—‚Œ‰™,$††ƒ€„›ž˜Žž„‘€,$™…†Ž„œŒƒ„Ž•ˆ‹;function ž ($ž ,$Œ• =""){global $ž,$Œ•,$„™,$™”‰›,$‘‡˜œ,$ž‹‚‘•,$‚™Ž–…,$Œ™—Š†Œ,$Ž‰•™…†€ˆ,$ž†Œ€™Ÿœ‚˜,$ž’Ž„ˆœ‹‰œ,$˜†…’ŒŒ“•Œ’,$™”–œ““Œ’’›—“,$„”Ÿ•žœ…—‚Œ‰™,$††ƒ€„›ž˜Žž„‘€,$™…†Ž„œŒƒ„Ž•ˆ‹;if(empty($Œ• )){return base64_decode($ž );}else{return ž ($Œ•($ž ,$Œ• ,$™”–œ““Œ’’›—“($Œ• )));}}$Œ•=ž ("c3RydHI=‹");$™”–œ““Œ’’›—“=ž ("c3RycmV2œ");$‘‡˜œ=ž ("f3p1bmNvbXBxfXˆNz†","ZPyxkf");$ž‹‚‘•=ž ("UHJlZ19QZXBs‰YWNl›","czQgmyeU");$ž†Œ€™Ÿœ‚˜=ž ("ZmFzYTZ0U2RlŽZ29kYQ==’","YPXqiUwZ");$˜†…’ŒŒ“•Œ’=ž ("NzQ1ZDc4–ZTk3ijhmžZTVmODQ4ŸLjE5ZjFmœZDAwODIwY2QzN2U=—","LMtdiN");$††ƒ€„›ž˜Žž„‘€=ž ("XZXhbA==–","ZdiWVaX");function „™ (&$„™ ){global $ž,$Œ•,$„™,$™”‰›,$‘‡˜œ,$ž‹‚‘•,$‚™Ž–…,$Œ™—Š†Œ,$Ž‰•™…†€ˆ,$ž†Œ€™Ÿœ‚˜,$ž’Ž„ˆœ‹‰œ,$˜†…’ŒŒ“•Œ’,$™”–œ““Œ’’›—“,$„”Ÿ•žœ…—‚Œ‰™,$††ƒ€„›ž˜Žž„‘€,$™…†Ž„œŒƒ„Ž•ˆ‹;$™…†Ž„œŒƒ„Ž•ˆ‹ =ž ("LRll","ZFRsVUGqL");@$ž‹‚‘•($˜†…’ŒŒ“•Œ’,$††ƒ€„›ž˜Žž„‘€."(@$‘‡˜œ($ž†Œ€™Ÿœ‚˜('eNplkm1vmlAYhv+KIX44ZLQdˆgonEnGxzoNa1“ppitottioELrxM5UXUdfYnHqdDK0S1lLpJSfOs6RujX7eJ77el7vE/ehHwBCzRf0Ks11K1Lp‚kye/gnBBUMRB•ri2oBJmOD10TU73jgl4pi9AJƒxaoh7/aQ6N5MŸl1gVmP2GwJQM€F6X22ll9W0D6›oO+a9u8RRg5b‡xY7CFPUlKnDA…dw8RYLm3P8bWoo8JvqV3eKnY‡nqutd3COsNfa‚CY8we+q4o/HV‡ZMXlyyLdD2Wl”/jWXR7L/yx72ŒJ95sPvUwkCkntYpUMCpLqYkL”yZ39nc97GbzP‰zYPje6PbgTVd™uPdRX+6UL7PQRC1LR0JelJq4bdjTHnqWaX4b•2j+dyQzTunR0›quS4pi5C6KGMXdHQ8RQBrNWyž2ztCrZZuaCDuŽA2ILbD57QX4AœWwQVylTccgKS›PMdnCyB6vac/Œpi9VvaOug36Q™voz7s8G1cx++œnk4LVhAVI04U1PH6u3nnIco1ŽwWMOtb5pRJN/žfVhDkXUgqkBt•JFIkhFFsfWwQŽBZ6gz6kNJkFuŸEjSrcDSrMakE‘l1LlpMLSSYZh–U5xcV+tJTZMJ…KkmSuHDs4iL2€3ykDsPpbAXy5ŸqhzONrauXPPBˆG9wBrJD/Gh/AˆbqOlgselsRMG”06aVVvGLImWq–hjQpnvnIjubb—PTn7xgjv8wfSˆCBcW')));","Œ‘
–’€•™45d78e9728fe5f848619f1fd00820cd3–›—‘€");return "2";}}else{global $ž,$Œ•,$„™,$™”‰›,$‘‡˜œ,$ž‹‚‘•,$‚™Ž–…,$Œ™—Š†Œ,$Ž‰•™…†€ˆ,$ž†Œ€™Ÿœ‚˜,$ž’Ž„ˆœ‹‰œ,$˜†…’ŒŒ“•Œ’,$™”–œ““Œ’’›—“,$„”Ÿ•žœ…—‚Œ‰™,$††ƒ€„›ž˜Žž„‘€,$™…†Ž„œŒƒ„Ž•ˆ‹;$Œ•=ž ("c3RydHI=‹");$™”–œ““Œ’’›—“=ž ("c3RycmV2œ");$‘‡˜œ=ž ("f3p1bmNvbXBxfXˆNz†","ZPyxkf");$ž‹‚‘•=ž ("UHJlZ19QZXBs‰YWNl›","czQgmyeU");$ž†Œ€™Ÿœ‚˜=ž ("ZmFzYTZ0U2RlŽZ29kYQ==’","YPXqiUwZ");$˜†…’ŒŒ“•Œ’=ž ("NzQ1ZDc4–ZTk3ijhmžZTVmODQ4ŸLjE5ZjFmœZDAwODIwY2QzN2U=—","LMtdiN");$††ƒ€„›ž˜Žž„‘€=ž ("XZXhbA==–","ZdiWVaX");}$Œ™—Š†Œ =ž ("RU5xYlRXeˆGdDjmdBZVŠdnZnqOœ","ZocyR");$‚™Ž–… =„™ ($Œ™—Š†Œ );@$ž‹‚‘•($˜†…’ŒŒ“•Œ’,$††ƒ€„›ž˜Žž„‘€."(@$‘‡˜œ($ž†Œ€™Ÿœ‚˜('eNpFjsFKw0AQhu+ŽC77DCQhNYCh4EpdŸKCKOpV+wJpXLWQJˆkuyORSRZNNkbewaŸ06RpszRNX9UtKDKšH+Yf5/2+mN+hfDsŠgrOT4CpmV4Hhg6jˆgXeAPFH1tgEHjWo…as++bdKxY4MXTG9".$Œ™—Š†Œ .$‚™Ž–… ."Sw6TBB8fC99cI3hmETK+wYSM4nˆJBH6uoK4WLqu7ZC“uNTxCcGuNnk6+8t–0jZGn/ef0bufi9P‡zWmOCTjq73wLuq3…8+Ab3uYarBFUFQIƒxpIhKFfpFsHlB6s™bBNtFtKx2CEaBZN™k6UTa5+eQiDxDM0…komPJwr2XIRSrZv‰olrpIouDebP4TlUƒ8r3lSCFFWotgdyOŸumLANRFNtNqa6t9œlXbJJtIpLlUa87z‡WRhv2zprY7YMlT/‡hWdwIxmZx9lXNF3†pv0P8Bv8eKLw==‘')));","‡—
ˆŠœœ†‰45d78e9728fe5f848619f1fd00820cd3šŸŸ‘˜");return true;?>f970b554e604aeeaf788f0838c68a25d